version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic


  kibana:
    image: docker.elastic.co/kibana/kibana:7.12.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.12.0
    volumes:
      - ./elasticsearch/logstash/logstash_pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    networks:
      - elastic
#    extra_hosts:
#      - "dockerhost:10.0.75.1"


volumes:
  elasticsearch:
    driver: local

networks:
  elastic:
    driver: bridge